title: Default Page

tabs:

  # Content
  content:
    label: Content
    icon: text
    preset: page
    fields:
      text:
        label: Text
        type: textarea
        size: large
  
  # Meta
  meta: tabs/seo/meta



